config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root "sessions#new"
  post "sessions" => "sessions#create"
  delete "sessions" => "sessions#destroy"
  resources :users do
    resources :photos, only: [:index, :new, :create]
  end
  resources :external_services, only: [] do
    collection do
      post :auth
      post :tweet
    end
  end
  get  "oauth/callback"  => "external_services#callback"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_photos

  validates :display_id, presence: true, uniqueness: true
  validates :password_digest, presence: true

  has_secure_password
end

app/models/user_photo.rb
class UserPhoto < ApplicationRecord
  belongs_to :user
  has_one_attached :image

  validates :title, presence: true, length: { maximum: 30 }
  validates :image, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_user
    @curren_user ||= User.find_by(id: session[:user_id])
  end

  def authenticate?
    redirect_to root_path unless current_user.present?
  end
end

app/controllers/external_services_controller.rb
class ExternalServicesController < ApplicationController
  before_action :authenticate?

  def tweet
    request_params = {
      text: params[:text],
      url: params[:image_url]
    }
    headers = {
      "Content-Type" => "application/json",
      "Authorization" => "Bearer #{session[:access_token]}"
    }
    uri = URI.parse(ENV['TWEET_URL'])
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = uri.scheme === "https"
    response = http.post(uri.path, request_params.to_json, headers)
    p response.body if response.code != 200

    redirect_to user_photos_path(current_user)
  end

  def auth
    uri = URI.parse(ENV['AUTH_URL'])
    uri.query = URI.encode_www_form(
      {
        client_id: ENV['CLIENT_ID'],
        response_type: 'code',
        redirect_uri: ENV['REDIRECT_URL']
      }
    )
    redirect_to uri.origin + uri.request_uri
  end

  def callback
    request_params = {
      code: params[:code],
      client_id: ENV['CLIENT_ID'],
      client_secret: ENV['CLIENT_SECRET'],
      redirect_uri: ENV['REDIRECT_URL'],
      grant_type: "authorization_code"
    }
    uri = URI.parse(ENV['AUTH_POST_URL'])
    response = Net::HTTP.post_form(uri, request_params)
    parsed_body = JSON.parse(response.body)
    session[:access_token] = parsed_body['access_token']
    redirect_to user_photos_path(current_user)
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authenticate?
  before_action :set_user
  before_action :set_url_options, only: [:index]
  def index
    @user_photos = @user.user_photos
  end

  def new
    @user_photo = @user.user_photos.build
  end

  def create
    @user_photo = @user.user_photos.build(user_photo_params)
    if @user_photo.save
      redirect_to user_photos_path(current_user)
    else
      render :new
    end
  end

  private

  def user_photo_params
    params.require(:user_photo).permit(:title, :image)
  end

  def set_user
    @user = User.find(params[:user_id])
  end

  def set_url_options
    ActiveStorage::Current.host = request.host
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :set_user, only: [:create]
  before_action :authenticate?, only: [:destroy]
  before_action :logged_in?, only: [:new, :create]

  def new; end

  def create
    if @user.present? && @user.authenticate(params[:password])
      login(user: @user)
      redirect_to user_photos_path(current_user)
    else
      failure_messages = []
      failure_messages.push('ユーザーIDを入力してください') if params[:display_id].blank?
      failure_messages.push('パスワードを入力してください') if params[:password].blank?
      flash[:failure] = failure_messages.presence || ['ユーザーIDまたはパスワードが正しくありません']
      redirect_to root_path
    end
  end

  def destroy
    logout
    redirect_to root_path
  end

  private

  def set_user
    @user = User.find_by(display_id: params[:display_id])
  end

  def logged_in?
    redirect_to user_photos_path(current_user) if current_user.present?
  end

  def login(user:)
    session[:user_id] = user.id
  end

  def logout
    session[:user_id] = nil
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/external_services_helper.rb
module ExternalServicesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/_flash.html.erb
<div style="color: red;">
  <% flash.each do |key, value| %>
    <% if key == 'failure' %>
      <ul>
        <% value.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
  <% end %>
</div>

app/views/layouts/_model_error_message.html.erb
<div style="color: red;">
  <ul>
    <% model.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhotoAlbum</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/photos/index.html.erb
<div>
  <%= link_to "ログアウト", sessions_path, method: :delete %>
  <br>
  <h1>写真一覧</h1>
  <%= link_to "MyTweetAppと連携", auth_external_services_path, method: :post %>
  <br>
  <%= link_to "写真をアップロード", new_user_photo_path(@user) %>
  <br>
  <% @user_photos.reverse.each do |user_photo| %>
    <div style="float: left; margin: 10px;">
      <div>
        <p><%= user_photo.title %></p>
        <%= image_tag user_photo.image.representation(resize_to_limit: [200, 200]) %>
        <%= button_to 'ツイートする', tweet_external_services_path(title: user_photo.title, image_url: rails_representation_url(user_photo.image.variant({}), only_path: false)), method: :post %>
      </div>
    </div>
  <% end %>
</div>

app/views/photos/new.html.erb
<div>
  <%= link_to "ログアウト", sessions_path, method: :delete %>
  <br>
  <h1>写真アップロード</h1>
  <%= render partial: "layouts/model_error_message", locals: { model: @user_photo } %>
  <%= form_with model: @user_photo, url: user_photos_path, method: :post do |form| %>
    <%= form.label :title, "タイトル：" %>
    <%= form.text_field :title %>
    <br>
    <%= form.label :image, "画像ファイル：" %>
    <%= form.file_field :image %>
    <br>
    <%= form.submit "アップロード" %>
    <br>
    <%= link_to "キャンセル", user_photos_path(@user) %>
  <% end %>
</div>